### ISSUE TITLE
Installation of Furan Analog in DCNYS Page

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series3#10]
@mbhebhe We need to get the furan analog target installed on the [DCNYS](https://github.com/OpenSourceMalaria/Series3/wiki/Desirable-Compounds-Not-Yet-Synthesised) page, up top, since it's being actively pursued. Can you look at the [corresponding S4 page](https://github.com/OpenSourceMalaria/Series4/wiki/Desirable-Compounds-Not-Yet-Synthesised) for what's needed and add the necessary data/strings to the top of the S3 page. If you can upload the image of the furan compound to the [relevant wiki folder](https://github.com/OpenSourceMalaria/Series3/tree/master/Wiki%20Files/DCNYS) I can add it to the wiki (though by looking at the [relevant S4 wiki page](https://github.com/OpenSourceMalaria/Series4/wiki/Desirable-Compounds-Not-Yet-Synthesised), you can probably work out how to do this yourself by copying/pasting/modifying the relevant text?

Once it's there, can you add any links to relevant Github issues talking about the synthesis of this compound, again as per the S4 page, so that we have no orphan issues? Once all done we can add in the links to the current Google docs you have that describe the synthetic chemistry synopsis. Once that's all done we can close this Issue.

**Comment by MFernflower** [comment]
I do wonder if getting a quote from a custom synthesis company would be a
good idea @mattodd

**Comment by MFernflower** [comment]
@mbhebhe I see you are using triphenylphosphine in your Staudinger Reduction - IIRC @mcoster has had better results using tributyl or triethylphosphine

**Comment by MFernflower** [comment]
@mbhebhe have you obtained any reduced product?

**Comment by MFernflower** [comment]
@mbhebhe this might be of use to you https://link.springer.com/article/10.1007%2FBF02974006

**Comment by MFernflower** [comment]
Closing this - check the S3 wiki DCNYS @mattodd
