### ISSUE TITLE
Compounds for biological testing Nov 2018 (including SGS-UNC compounds)

### ISSUE THREAD

**Issue by mbhebhe** [OpenSourceMalaria/Series3#11]
Compounds for biological testing. #
**USyd samples to be sent end of next week**.
OSM-S-606 is a product of the bromination of pyrrole occurring at the 7th position. 
OSM-S-137 (slightly active at 1.7 uM) was re-synthesized for sending to [Kansas State Uni](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/573) and UNC for kinome testing.
OSM-S-145 was synthesised but not tested and came across it in the fridge.

**SGS-UNC samples to be sent soon.** 
These samples were made by Alfredo Picado from SGS-University of North Carolina. They are similar to our Series 3 compounds. We will see if they have any activity. #8 

![image](https://user-images.githubusercontent.com/26862286/48242442-5b3b2a00-e42f-11e8-996b-f10bbf843fe2.png)

![image](https://user-images.githubusercontent.com/26862286/48242463-7443db00-e42f-11e8-9542-4c1527982dff.png)

These compounds will be sent with the S4 compounds. Once we have the biological data, it can be found on [here](https://github.com/OpenSourceMalaria/Series4/issues/62) 

[November 2018 Dundee.zip](https://github.com/OpenSourceMalaria/Series3/files/2564549/November.2018.Dundee.zip)

**Comment by MFernflower** [comment]
@mbhebhe do you have the required acid to make the carboxylic acid analogue of the original hit?

**Comment by MFernflower** [comment]
considering how close our lead is to caboxamycin - do you think it'd be worth coupling the core to some two and three hydroxyphenyl boronic acid? @mbhebhe @holeung

**Comment by MFernflower** [comment]
Closing this issue - see https://github.com/OpenSourceMalaria/Series4/issues/62 for potency results once they come in!
