### ISSUE TITLE
Samples for biological testing 

### ISSUE THREAD

**Issue by mbhebhe** [OpenSourceMalaria/Series3#18]
Samples from Series 3 have been sent to Dundee for biological testing. 
Our MSc student synthesised OSM-S-106 and OSM-S-123 for the carbonic anhydrase assay #14 and I have synthesised more OSM-S-137.

![image](https://user-images.githubusercontent.com/26862286/63273313-abd09500-c295-11e9-98ba-34f87faa6abb.png)

**Comment by mbhebhe** [comment]
Results are in, you can find them [here](https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/NjMwLjV8MjcwNjkvNDg1LTIyMDEvVHJlZU5vZGUvMTc1NjQzMjk2MXwxNjAwLjU=)

![image](https://user-images.githubusercontent.com/26862286/65331110-feaeac80-dbb3-11e9-8af8-bd613d8c5c2e.png)

**Comment by drc007** [comment]
So carbonic anhydrase inhibition seems to reflect Pfal activity at least in terms of rank order?

<img width="436" alt="threeselect" src="https://user-images.githubusercontent.com/7080516/65332945-8649ea80-dbb7-11e9-9f06-fe1199ec2b33.png">

**Comment by mbhebhe** [comment]
These are the biological evaluation results. The OSM-S-106 and OSM-S-123 results are not consisted with the previous results from previous batches.
We are yet to send OSM-S-106 and OSM-S-123 for the Hs and Pf CA assay.

**Comment by MFernflower** [comment]
Seems like CA is either real target and we barked up the wrong tree with
the protien synthesis assays OR it's a co-target and main target
(Kinase??????) Is yet to be found

@drc007 @mattodd
