### ISSUE TITLE
CRISPR editing 

### ISSUE THREAD

**Issue by mbhebhe** [OpenSourceMalaria/Series3#19]
Our collaborators at the Wellcome Sanger Institute did some CRISPR editing to confirm that the Asn-tRNA ligase mutation is causal for resistance. The mutant parasite was generated by using CRISPR gene editing. They introduced the R487S mutation that came up in the selection with the most resistant clone (#12 ). Then, the isogenic mutant parasite underwent a drug response assay with OSM-S-106 to determine IC50 value in parallel with the wild-type Asn-tRNA ligase parasite (in this case they used both Dd2 and 3D7 wild type strains). Their most recent work can be found [here](https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/NzA0LjZ8MjcwNjkvNTQyLTIzNTUvVHJlZU5vZGUvMTM3ODY3ODA3OXwxNzg4LjY=)

**Comment by MFernflower** [comment]
If the T-RNA synthease isn't the target but allows for resistance perhaps
our drug targets the synthesis of the amino acid itself? @mattodd

>

**Comment by MFernflower** [comment]
@mattodd perhaps the molecule behaves as a competitive asparagine
synthetase inhibitor at the ATP binding site? @mbhebhe

**Comment by drc007** [comment]
@mbhebhe Do you know if the mutated enzyme is still functional?

**Comment by holeung** [comment]
We know for sure that Asn-ligase is not the target?

**Comment by mbhebhe** [comment]
@MFernflower if 106 binds to the ATP binding site then that would affect translation. We have seen that the molecule does not inhibit translation. 
@drc007 I will ask them.
@holeung not completely. It could still be the target.

**Comment by MFernflower** [comment]
@mbhebhe I have a hunch that while it doesn't bind to the enzyme that loads empty transfer RNA's with asparagine - it might bind to the enzyme that converts aspartic acid to asparagine, thus lowering the malarial cells pool of asparagine to dangerous levels culminating in cell death

**Comment by MFernflower** [comment]
@mbhebhe @drc007  I have a hunch that while it doesn't bind to the enzyme that loads empty transfer RNA's with asparagine - it might bind to the enzyme that converts aspartic acid to asparagine, thus lowering the protist's pool of asparagine to fatal levels - somebody could confirm this by measuring levels of an ASN rich protein - if after drugging the levels fall sharply, then we may have our MOA!

**Comment by mbhebhe** [comment]
They don't know if the mutated enzyme is still functional. They would need to engineer it as a recombinant protein and then have it tested in an in vitro assay. If they assume the protein is essential, then it presumably is still functional.

**Comment by MFernflower** [comment]
@holeung The sequence of Plasmodium Vivax ASNS is known - Would you be able to try to model and dock 106 to it?

>tr|A5KBA9|A5KBA9_PLAVS Asparagine synthetase [glutamine-hydrolyzing], putative OS=Plasmodium vivax (strain Salvador I) OX=126793 GN=PVX_119585 PE=4 SV=1
MCGILAIFHSSIERHRLRRKALELSKKLRHRGPDWNGIVVEENEDGTTNVLAHERLAIVD
VLSGHQPLYDDAQEVCLTINGEIYNHMELRKLLPEDTIKKLTSHSDCAVIPNLYKNFGEK
TPSMLNGIFSGVISDHKKNTFFAFRDPIGVCPLYIGYAADGSIWFASEFKALKDSCIRYV
NFPPGHYYINCKNKGEFVRYFNPNWWDLSAAIPNNRADLEQIRVHLERAVVKRLMGDVPF
GVLLSGGLDSSIVAAIVARHLKKIQGEGSGGGSGAAAAHQAAHEASPPNGEDNCGNPPAD
SCHLKSFSIGLRNSPDLKAAKEVANFLGSHHTEFHFTVEEGVDSLHDVIYHIETYDITTI
RASTPMYILSRLIKSSCVKMVLSGEGADEIFGGYLYFHKAPNREEFHRELQRKVHDLHLY
DCLRANKSTMAFGIEARVPFLDLHLLDVVMNIDPKEKMCSEGHIEKDILRRAFAGYLPDH
ILYRQKEQFSDGVGYNWIDGLKEYAESKVSDIQFSRAPFLFPYNTPKTKEAYLYRCIFSE
CFPEQCAQESVPEGSSIACSSSKAVEWDASFKQNPDQSGRSVLGVHHSAKQFADVKPVQL
PDDESRALLTRAS

**Comment by mattodd** [comment]
Closing. This page is linked on the wiki. The data linked at the top of the page supported Asn-tRNA synthetase as the target.
