### ISSUE TITLE
OSM-Furan

### ISSUE THREAD

**Issue by mbhebhe** [OpenSourceMalaria/Series3#2]
**# Ideas on brominating OSM-Furan before ring closure**
![image](https://user-images.githubusercontent.com/26862286/37885174-79067bd6-30ff-11e8-82e6-8b601b0f9e3a.png)
DOI: 10.1039/c6ob01657j (procedure in SI)

![image](https://user-images.githubusercontent.com/26862286/37885199-a0b1328e-30ff-11e8-8973-a08609de97cb.png)
https://doi.org/10.1002/chem.201504330 (procedure in SI)

![image](https://user-images.githubusercontent.com/26862286/37885267-f5e8d95a-30ff-11e8-92e2-b8c16f2d9c51.png)
https://doi.org/10.1016/j.tet.2016.09.026 (procedure in SI)

**Comment by MFernflower** [comment]
@mbhebhe has this been added to the main OSMFuran googledoc?

**Comment by MFernflower** [comment]
@mbhebhe @mattodd Perhaps a synthchem update is warranted? I have not a clue as to what new analogues were made successfully

**Comment by mbhebhe** [comment]
They are still in progress

**Comment by MFernflower** [comment]
@mbhebhe Is there a plan for a lab update? It's been a while since I looked at S3

**Comment by mbhebhe** [comment]
Before the lab shut down I was in the middle if these reactions. Planning on going back into the lab soon to carry on the chemistry. Hoping these reactions will work.
Any suggestions on the chemistry are welcome, especially on the Sonogashira coupling on the Cl

![image](https://user-images.githubusercontent.com/26862286/88018294-06cfd380-cb5a-11ea-95c0-343a2758134b.png)

**Comment by MFernflower** [comment]
A total shot in the dark but there is some precedent to replacing the
traditional palladium complexes with Palladium(II)
5,10,15,20-(tetra-p-tolyl)porphyrin

https://www.organic-chemistry.org/abstracts/lit6/333.shtm

A company called PorphyChem has it in stock but pricing is done by request
so maybe reach out to them?

**Comment by MFernflower** [comment]
@mbhebhe PorphyChem sells the 5,10,15,20-(tetra-p-tolyl)porphyrin without the metal for cheap - I think you can install the metal using PdCl2, acetonitrile, and dichloromethane

**Comment by mattodd** [comment]
Closing. [Link installed on wiki](https://github.com/OpenSourceMalaria/Series3/wiki/Desirable-Compounds-Not-Yet-Synthesised).
