### ISSUE TITLE
Homology Model of Pf asparagine-tRNA ligase

### ISSUE THREAD

**Issue by mbhebhe** [OpenSourceMalaria/Series3#20]
We have been working with Prof. Haider Shozeb at UCL. He has modeled a homology model of Pf asparagine-tRNA ligase based on the Hs one. The homology model is 36% similar to the actual ligase but the binding site is very much similar. He believes that the predictions should be accurate. He is yet to touch up and fix up the model. 

The volume of the pocket is 379.4. OSM-S-106 does not fill the whole pocket and can be made longer in the north east region (where the sulfonamide is). He generated a list of 141 isosteres for the sulfonamide. I had a look at our S3 library and we have only synthesised 3 compounds (OSM-S-649, OSM-S-135, OSM-E-34), which were all inactive. He is yet to have a look at these three to try and improve his model. The 6-phenylthieno[3,2-d]pyrimidin-4-amine does not need to be altered as it fits perfectly in the binding pocket, based on Hs AsnRS with bound AsnAMP (DOI 10.1002/jcc.21414). 

The next step would be to improve the model and then start looking at molecules to synthesise based on increasing the volume of 106 and choosing an isostere that will interact with protein residues in the pocket to improve potency.

The preliminary data can be found [here](https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/NzI1LjR8MjcwNjkvNTU4L1RyZWVOb2RlLzIwMDAzMDYwMDh8MTg0MS4zOTk5OTk5OTk5OTk5). 

![image](https://user-images.githubusercontent.com/26862286/71300876-17845500-2391-11ea-8d4d-5cb452f88df2.png)

![image](https://user-images.githubusercontent.com/26862286/71299871-0420bc00-2388-11ea-89b4-651a04386487.png)

![image](https://user-images.githubusercontent.com/26862286/71299860-ea7f7480-2387-11ea-84c3-9fb777c9a487.png)

![image](https://user-images.githubusercontent.com/26862286/71300946-9f6a5f00-2391-11ea-92f8-8ce6ccbe68ed.png)

**Comment by MFernflower** [comment]
Has the n-monomethylated-sulfonamide ever been tested? @mbhebhe

**Comment by mbhebhe** [comment]
@MFernflower yes it has been tested and it was inactive

**Comment by yinuowang0812** [comment]
I am currently working on a project that aims to improve the potency of the Open Source Malaria Series 3 lead compound (OSM-S-106) based on a new crystal structure of OSM-S-106 bound to the relevant target, Pf asparagine tRNA synthetase. This molecule has shown good human microsomal and rat hepatocyte clearance data. 

Currently we are not sure about the docking of Pf asparagine tRNA synthetase and OSM106 molecule. Is anyone have an idea about the crystal structure of Pf asparagine tRNA synthetase?

**Comment by mattodd** [comment]
Hey there @yinuowang0812 - welcome on board! (Everyone - Yinuo works in my lab in UCL and has just started a PhD).

We've been working with Leann Tilley in Melbourne on the structure and will be able to share details very soon (alongside an explanation as to why we've not shared it yet).

So the question is: can Alphafold help us to get an approximation of the structure that we might be able to use? So

1) Is the structure in Alphafold? @yinuowang0812 did you want to check?
2) Is the structure useful (someone told me that AF does badly with homodimers?). We'd want to try to dock OSM-S-106 inside and then explain our SAR.

**Comment by mattodd** [comment]
Closing. This page linked on the wiki. Homology model superceded by one in forthcoming paper. AlphaFold indeed used.

**Comment by yinuowang0812** [comment]
[like]  Wang, Miss Yinuo Wang reacted to your message:
________________________________
