### ISSUE TITLE
Links to currently active Google Docs and other paper drafts

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series3#23]
Hi @mbhebhe - when you've a moment could you link somewhere (front page, or wiki) to any and all currently active Google docs or word files that you've been using to assemble the Series 3 paper? New biology results (coming ASAP all - from collaborators, so just verifying what can be said) mean we need to write up what we know, and it's important we don't lose what we started. Once we've installed the links, we can close this issue.

Also, if you've useful files for the papers, we need to put those on this repo too - diagrams, pix etc. Raw data should stay on your ELN. I can upload, or you can drag to a relevant folder.

**Comment by mbhebhe** [comment]
Open Source Malaria Series 3: Initial Data and Mechanism of Action of a Promising Antimalarial Class ([MoA paper](https://docs.google.com/document/d/1knEIKTmouubLBNEnlveFEJZzEPWGTfgUFLGUUm5q12k/edit#)), Validated and pre-validated antimalarial targets [Review](https://docs.google.com/document/d/17GE_vccDPBJHH3zp8aiTnXjbEVHXt0S937kFOGhWxJs/edit) and [SI](https://docs.google.com/document/d/1ZGv2zVuRj-Nb1JXD9x9KzJOItIVyfbmSvdOxcHJBBnc/edit) for S3

**Comment by mattodd** [comment]
Closed. Superceded and MoA paper linked from wiki. Don't have access to the other two links above.
