### ISSUE TITLE
Compound OSM-S-106 sent for biotransformation experiment

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series3#3]
A series 3 compound, OSM-S-106, was included along with four series 4 compounds in a shipment on 6/4/18 to Pfizer to look at possible biotransformations in liver microsomes. 

[ELN link](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/MjQ3LjB8MzAxNzEvMTkwL1RyZWVOb2RlLzEzMzU0MzIwMzl8NjI3LjA=)

![pfizer april 2018 compounds sent](https://user-images.githubusercontent.com/30584472/38406268-8b4dcb9e-39b7-11e8-840c-c501a7fe6235.jpg)
[Pfizer April 2018 Compounds Sent.zip](https://github.com/OpenSourceMalaria/Series3/files/1882932/Pfizer.April.2018.Compounds.Sent.zip)

*Strings
OSM-S-106
MNB 6-7NC1=C2C(C=C(C3=CC(S(N)(=O)=O)=CC=C3)S2)=NC=N1
InChI=1S/C12H10N4O2S2/c13-12-11-9(15-6-16-12)5-10(19-11)7-2-1-3-8(4-7)20(14,17)18/h1-6H,(H2,13,15,16)(H2,14,17,18)
MQMXDJVOZKMSNT-UHFFFAOYSA-N*

**Comment by MFernflower** [comment]
@mattodd any followup from this?

**Comment by mattodd** [comment]
Have chased Scott's team. Can't find original data. Would be interesting to know. Closing, but have installed link to this issue on wiki.
