### ISSUE TITLE
Starting the Composite Synthetic Chemistry Document

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series3#4]
The [composite Google Doc of supporting info-style write-up of the Series 3 organic chemistry](https://docs.google.com/document/d/1XBei-FAONxOuAkBOgk-p2wN-8rj3XZmvHUtoM5Syc3I/edit?usp=sharing) is coming together. We need to consolidate all reports of syntheses, or at least keep all reports of synthesis of a certain molecule together. We will need a simple version of this for submission of a paper.

I've added a folder to the Series 3 repo under "Reports and Theses" called Supporting Info Style Docs which contains that Word Doc with the composite characterization data and procedures in it dating back from when Series 3 was first examined. @mbhebhe can you please look at the first synthetic report contained in there (as a tester) and think about whether we need it? How does it relate to your write-up for MNB1? Do we need both? I don't have an answer here, but I want to know how we keep track of all these write-ups. Do we have one "exemplar" write-up, and simply link out to all the others?

Can you also please think about how we keep track of the spectroscopic data? The write-up for the paper will need the traditional style write-up of NMR, MS etc (as we have it). But should we not also be linking to raw data that are housed somewhere? Is it enough that we link to the ELN page containing the data? That way we can generate the image versions of the spectra later when we submit?

I think the Google Doc needs the strings for each molecule added (SMILES, InChI and INCHIKEY? Unless you think these are not needed for some reason?

Once we have an agreed strategy in place we can add that strategy to OSM somewhere - we are facing many of the same issues over on the Series 4 paper 1 repo. But let's start with MNB1

**Comment by drc007** [comment]
@mbhebhe Please continue to include SMILES. The InChi format is was only really intended to be an identifier and there is not a guarantee that they can converted back into an unambiguous structure.

**Comment by mattodd** [comment]
Closing. The Google Doc is linked from the wiki, but is no longer actively maintained. Have also taken a download and placed on my ELN and on Github.
