### ISSUE TITLE
Identification of Old Paul Willis Molecule Suggestions that Need Adding to DCNYS

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series3#5]
@mbhebhe can you please take a look at the Github file Wiki Files>DCNYS>Paul Willis_Thienopyrimidine new targets. Please can you see whether any of the compounds in the Chemdraw file have been completed (_vs_ the [list of all compounds made to date](https://docs.google.com/document/d/1r-jJ0t4YuP3zsFnIPSM2K_cZjsak3JJhqNrfwMGr5Sw/edit))? If they have, create a new ("V2") version of this Chemdraw file that shows which compounds have been made (black, with an OSM number) and which are still needed (in red). The ones that are still needed will need to be added to the DCNYS page, and we can create a new Issue for that when the required structures have been identified.

**Comment by mbhebhe** [comment]
![image](https://user-images.githubusercontent.com/26862286/39417006-b03b8294-4c94-11e8-9c05-e57905f6f768.png)
What's written in blue is mine. 
Six of the compounds have been made but one (OSM-S-145), has not been sent for biological evaluation yet.
The ones in red need to be made, for some of them we have the two halves that need need to be coupled together (hopefully are in the fridge).

**Comment by drc007** [comment]
Sorry if I have missed it, but have we remade and tested the original hit?

**Comment by mbhebhe** [comment]
@drc007 yes we have, it has been made and all the data is [here on the wiki](https://github.com/OpenSourceMalaria/Series3/wiki/The-Data-on-the-Original-Hit).
I recently made more and it has been sent to Dundee for biological evaluation and if its good, I will send some to Ho Leung's lab.

**Comment by MFernflower** [comment]
A wee bit unrelated but has this compound ever been tested? @mattodd @mbhebhe 

![111111111111123](https://user-images.githubusercontent.com/3164942/40091863-2605b306-5888-11e8-9764-474b3c2ed246.png)

**Comment by MFernflower** [comment]
@mbhebhe Have not seen updates from you in a while - has synthesis of any of the ring analogues been completed as of late?

**Comment by mbhebhe** [comment]
Not complete yet, they are still in progress

**Comment by MFernflower** [comment]
Closing this - it appears that OSM-S-145 and OSM-S-437 need to be re-synthesized and send off for testing
