### ISSUE TITLE
April 2018 Dundee Results for OSM-S-106

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series3#6]
Two batches of OSM-S-106 were included in the [April 2018](https://github.com/OpenSourceMalaria/Series4/issues/39) Dundee shipment.

![image](https://user-images.githubusercontent.com/30584472/41893456-25b6d14e-795f-11e8-9d71-5886f22549f9.png)

The first sole result came back overnight - 98 nM - this is just one run of one of the batches. It is in agreement with previous samples. Will update when we have the full set of data, and @mbhebhe will then upload to all the usual places.

**Comment by david1597** [comment]
Potency results are trickling through. We now have two runs for one batch, and the first run for the other batch. The two runs for MNB6-9 were in good agreement (96 and 98 nM), and slightly lower than a previous batch measured at Dundee (130 nM).

![image](https://user-images.githubusercontent.com/30584472/42144364-f8b14e56-7dfd-11e8-9266-68cd6130f869.png)

**Comment by mattodd** [comment]
Closing - added link to wiki, but don't have a link to any raw data, unless [here](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/MjQ3LjB8MzAxNzEvMTkwL1RyZWVOb2RlLzEzMzU0MzIwMzl8NjI3LjA=)?
