### ISSUE TITLE
Sharing of compounds with Alfredo Picado from SGC?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series3#8]
@mbhebhe check out [this tweet](https://twitter.com/SGClabNotebooks/status/1044938945946161153), and see if there is a way to share compounds/expertise.

**Comment by mattodd** [comment]
Compounds are being made by David Drewry's group at the SGC at UNC. Exploring whether we can cross-screen compounds.

**Comment by MFernflower** [comment]
closed - all test results including of Alfredo's molecules can be seen here: https://github.com/OpenSourceMalaria/Series4/issues/65
